name: 'Edit PR'

on:
  pull_request:
    type: [opened, reopened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          pr-number: ${{github.event.number}}
